server:
  port: 8082

spring:
  application:
    name: user-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USER}
    password: ${USER_DB_PASSWORD}

  flyway:
    mixed: true


